name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go env
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: touch release.txt && echo "testtt" >> release.txt

    - name: Set package version
      run: echo "VERSION=$(cat ${GITHUB_EVENT_PATH} | jq -r '.release.tag_name')" >> $GITHUB_ENV && env && git tag ${{ env.VERSION }}

    - name: Publish the Klaabu binary
      uses: softprops/action-gh-release@v1
      if: github.ref == 'refs/heads/master'
      with:
        tag_name: ${{ github.ref }}
        files:
          release.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
